### ISSUE TITLE
feat!: disable azure container registry admin (SNYK-CC-AZURE-594)

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-acr#33]
**Message:** Azure Container Registry Admin is enabled ([SNYK-CC-AZURE-594](https://snyk.io/security-rules/SNYK-CC-AZURE-594))
**Severity:** `Medium`

 Detailed paths

    Introduced through: resource › azurerm_container_registry[this] › admin_enabled

This issue is...
- Azure Container Registry Admin is enabled

The impact of this is...
- The admin user account is a technical account that allows depersonalized access and should be replaced by personalized, managed identities.

You can resolve it by...
- Set admin_enabled to false, or remove the property from the resource

#### References
- [Authenticate with an Azure container registry](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#admin-account)
- [Microsoft.ContainerRegistry registries](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerregistry/registries?tabs=json&pivots=deployment-language-terraform)
- [AzPolicyAdvertizer - Container registries should have local admin account disabled.](https://www.azadvertizer.net/azpolicyadvertizer/dc921057-6b28-4fbe-9b83-f7bec05db6c2.html?desc=compareJson&left=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2Fdc921057-6b28-4fbe-9b83-f7bec05db6c2_1.0.0.json&right=https%3A%2F%2Fwww.azadvertizer.net%2Fazpolicyadvertizerjson%2Fdc921057-6b28-4fbe-9b83-f7bec05db6c2_1.0.1.json)

**Comment by hknutsen** [comment]
Sounds like a good idea to disable the non-personal admin account by default. Would be a breaking change though, so I'd prefer if we explain how to upgrade in the commit, e.g:

```plaintext
feat!: disable admin account

BREAKING CHANGE: admin account disabled by default. To upgrade, set `admin_enabled` to `true`.
```
