### ISSUE TITLE
refactor: enable geo replication for acr images (SNYK-CC-AZURE-595)

### ISSUE THREAD

**Issue by helenakallekleiv** [equinor/terraform-azurerm-acr#34]
**Message:**  Geo replication for Azure Container Images disabled ([SNYK-CC-AZURE-595](https://snyk.io/security-rules/SNYK-CC-AZURE-595))
**Severity:** `Low`

Detailed paths

    Introduced through: resource › azurerm_container_registry[this] › georeplications

This issue is...
- Geo replication for Azure Container Images disabled

The impact of this is...
- Missing geo replication leads to reduced availability of container images

You can resolve it by...
- Set a georeplications block within the resource, including a valid location property

#### References
- [Microsoft.ContainerRegistry registries/replications](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerregistry/registries/replications?tabs=json&pivots=deployment-language-terraform)
- [Azure Container Registry makes geo-replication generally available, adding lifecycle management capabilities](https://azure.microsoft.com/en-gb/blog/azure-container-registry-makes-geo-replication-generally-available-adding-lifecycle-management-capabilities/)
- [Geo-replication in Azure Container Registry](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/container-registry/container-registry-geo-replication.md)

**Comment by hknutsen** [comment]
Should definitely be an optional feature.

**Comment by helenakallekleiv** [comment]
Geo-replication is only availiable for SKU-tier `Premium`, and should be noted in the description.

Ref.:
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry#georeplications
- https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/container-registry/container-registry-geo-replication.md#geo-replication-pricing

**Comment by helenakallekleiv** [comment]
Should we include an example (e.g. `geo-replication`), with SKU-tier `Premium` and geo-replication location e.g. `"Norway East"`?
